name: Locust Load Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      RZLT_HOST:
        type: string
        default: "https://risk.staging.redzone.zon"
        description: "Load testing server base URL"
        required: true
      RZLT_RUNTIME_MINUTES:
        type: string
        default: "5"
        description: "Load testing run time in minutes"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install locust

      - name: Run Locust Load Test
        env:
          RZLT_HOST: ${{ secrets.RZLT_HOST }}
          RZLT_RUNTIME_MINUTES: ${{ secrets.RZLT_RUNTIME_MINUTES }}
          RZLT_USERS: ${{ secrets.RZLT_USERS }}
          RZLT_ORG: ${{ secrets.RZLT_ORG}}
          RZLT_API_TOKEN: ${{ secrets.RZLT_API_TOKEN }}
        run: |
          locust --locustfile test/locustfile.py \
            --host ${{ github.event.inputs.RZLT_HOST }} \
            --run-time ${RZLT_RUNTIME_MINUTES}m \
            --spawn-rate 10 \
            --users ${RZLT_USERS} \
            --stop-timeout 10s \
            --autostart

      - name: Upload Locust Report
        uses: actions/upload-artifact@v4
        with:
          name: locust-results
          path: locust_report*

      - name: Commit results into branch
        run: |
          git fetch
          git checkout load-testing-results
          LOCUST_RESULTS=locust-results-$(date '+%Y-%m-%d-%H-%M-%S')
          mkdir ${LOCUST_RESULTS}
          cp locust_report_* ${LOCUST_RESULTS}
          git add ${LOCUST_RESULTS}
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -m "Load testing results" 
          git push