name: Locust Load Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install locust pandas jupyter matplotlib nbconvert

      - name: Run Locust Load Test
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          locust -f test/locustfile.py --headless --users 100 --spawn-rate 10 --run-time 1m --stop-timeout 10s --csv=locust_report -H https://presto.ibm.prestodb.dev

      - name: Run Jupyter Notebook to Process Locust Report
        run: |
          jupyter nbconvert --to notebook --execute test/process_locust.ipynb --output processed_results.
          jupyter nbconvert --to html processed_results.ipynb

      - name: Upload Locust Report
        uses: actions/upload-artifact@v4
        with:
          name: locust-results
          path: locust_report*

      - name: Upload Processed Jupyter Notebook
        uses: actions/upload-artifact@v4
        with:
          name: processed-results
          path: |
            processed_results.ipynb
            processed_results.html